// Code generated by protoc-gen-go. DO NOT EDIT.
// source: timepiece.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TimePiece struct {
	Timestamp            uint64   `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	OwnerID              string   `protobuf:"bytes,2,opt,name=ownerID,proto3" json:"ownerID,omitempty"`
	Source               string   `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimePiece) Reset()         { *m = TimePiece{} }
func (m *TimePiece) String() string { return proto.CompactTextString(m) }
func (*TimePiece) ProtoMessage()    {}
func (*TimePiece) Descriptor() ([]byte, []int) {
	return fileDescriptor_18925feecc07c261, []int{0}
}

func (m *TimePiece) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimePiece.Unmarshal(m, b)
}
func (m *TimePiece) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimePiece.Marshal(b, m, deterministic)
}
func (m *TimePiece) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimePiece.Merge(m, src)
}
func (m *TimePiece) XXX_Size() int {
	return xxx_messageInfo_TimePiece.Size(m)
}
func (m *TimePiece) XXX_DiscardUnknown() {
	xxx_messageInfo_TimePiece.DiscardUnknown(m)
}

var xxx_messageInfo_TimePiece proto.InternalMessageInfo

func (m *TimePiece) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *TimePiece) GetOwnerID() string {
	if m != nil {
		return m.OwnerID
	}
	return ""
}

func (m *TimePiece) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *TimePiece) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*TimePiece)(nil), "types.TimePiece")
}

func init() { proto.RegisterFile("timepiece.proto", fileDescriptor_18925feecc07c261) }

var fileDescriptor_18925feecc07c261 = []byte{
	// 136 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0xc9, 0xcc, 0x4d,
	0x2d, 0xc8, 0x4c, 0x4d, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2d, 0xa9, 0x2c,
	0x48, 0x2d, 0x56, 0xca, 0xe7, 0xe2, 0x0c, 0xc9, 0xcc, 0x4d, 0x0d, 0x00, 0xc9, 0x08, 0xc9, 0x70,
	0x71, 0x82, 0x94, 0x15, 0x97, 0x24, 0xe6, 0x16, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x04, 0x21,
	0x04, 0x84, 0x24, 0xb8, 0xd8, 0xf3, 0xcb, 0xf3, 0x52, 0x8b, 0x3c, 0x5d, 0x24, 0x98, 0x14, 0x18,
	0x35, 0x38, 0x83, 0x60, 0x5c, 0x21, 0x31, 0x2e, 0xb6, 0xe2, 0xfc, 0xd2, 0xa2, 0xe4, 0x54, 0x09,
	0x66, 0xb0, 0x04, 0x94, 0x27, 0x24, 0xc4, 0xc5, 0x92, 0x92, 0x58, 0x92, 0x28, 0xc1, 0xa2, 0xc0,
	0xa8, 0xc1, 0x13, 0x04, 0x66, 0x27, 0xb1, 0x81, 0xad, 0x37, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff,
	0xe7, 0x5b, 0xe5, 0x77, 0x91, 0x00, 0x00, 0x00,
}
