// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nodeHeader.proto

package p2p

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NodeHeader struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port                 string   `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`
	Secio                bool     `protobuf:"varint,3,opt,name=secio,proto3" json:"secio,omitempty"`
	Randseed             int64    `protobuf:"varint,4,opt,name=randseed,proto3" json:"randseed,omitempty"`
	Mode                 string   `protobuf:"bytes,5,opt,name=mode,proto3" json:"mode,omitempty"`
	PeerId               string   `protobuf:"bytes,6,opt,name=peerId,proto3" json:"peerId,omitempty"`
	FullAddr             string   `protobuf:"bytes,7,opt,name=fullAddr,proto3" json:"fullAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeHeader) Reset()         { *m = NodeHeader{} }
func (m *NodeHeader) String() string { return proto.CompactTextString(m) }
func (*NodeHeader) ProtoMessage()    {}
func (*NodeHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_679fc9ee91e52863, []int{0}
}

func (m *NodeHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeHeader.Unmarshal(m, b)
}
func (m *NodeHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeHeader.Marshal(b, m, deterministic)
}
func (m *NodeHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeHeader.Merge(m, src)
}
func (m *NodeHeader) XXX_Size() int {
	return xxx_messageInfo_NodeHeader.Size(m)
}
func (m *NodeHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeHeader.DiscardUnknown(m)
}

var xxx_messageInfo_NodeHeader proto.InternalMessageInfo

func (m *NodeHeader) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *NodeHeader) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *NodeHeader) GetSecio() bool {
	if m != nil {
		return m.Secio
	}
	return false
}

func (m *NodeHeader) GetRandseed() int64 {
	if m != nil {
		return m.Randseed
	}
	return 0
}

func (m *NodeHeader) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

func (m *NodeHeader) GetPeerId() string {
	if m != nil {
		return m.PeerId
	}
	return ""
}

func (m *NodeHeader) GetFullAddr() string {
	if m != nil {
		return m.FullAddr
	}
	return ""
}

func init() {
	proto.RegisterType((*NodeHeader)(nil), "p2p.NodeHeader")
}

func init() { proto.RegisterFile("nodeHeader.proto", fileDescriptor_679fc9ee91e52863) }

var fileDescriptor_679fc9ee91e52863 = []byte{
	// 169 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8e, 0xbf, 0xca, 0xc2, 0x50,
	0x0c, 0x47, 0xb9, 0x5f, 0xff, 0x7c, 0x35, 0x93, 0x04, 0x91, 0xe0, 0x54, 0x9c, 0x3a, 0x39, 0xe8,
	0x13, 0xb8, 0xe9, 0xe2, 0xd0, 0x37, 0xa8, 0x26, 0xa2, 0x50, 0x9b, 0x4b, 0x5a, 0x5f, 0xcb, 0x67,
	0x94, 0x7b, 0x2b, 0x77, 0xfb, 0x9d, 0x13, 0x38, 0x04, 0x96, 0x83, 0xb2, 0x9c, 0xa4, 0x63, 0xb1,
	0x9d, 0x37, 0x9d, 0x14, 0x33, 0xbf, 0xf7, 0xdb, 0x8f, 0x03, 0xb8, 0xa4, 0x0b, 0x22, 0xe4, 0x0f,
	0x1d, 0x27, 0x72, 0xb5, 0x6b, 0x16, 0x6d, 0xdc, 0xc1, 0x79, 0xb5, 0x89, 0xfe, 0x66, 0x17, 0x36,
	0xae, 0xa0, 0x18, 0xe5, 0xf6, 0x54, 0xca, 0x6a, 0xd7, 0x54, 0xed, 0x0c, 0xb8, 0x81, 0xca, 0xba,
	0x81, 0x47, 0x11, 0xa6, 0xbc, 0x76, 0x4d, 0xd6, 0x26, 0x0e, 0x95, 0x97, 0xb2, 0x50, 0x31, 0x57,
	0xc2, 0xc6, 0x35, 0x94, 0x5e, 0xc4, 0xce, 0x4c, 0x65, 0xb4, 0x3f, 0x0a, 0x9d, 0xfb, 0xbb, 0xef,
	0x8f, 0xcc, 0x46, 0xff, 0xf1, 0x92, 0xf8, 0x5a, 0xc6, 0xe7, 0x0f, 0xdf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xff, 0xa5, 0xd2, 0xdb, 0xd0, 0x00, 0x00, 0x00,
}
